// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Carousel: typeof import('./components/Carousel.vue')['default']
    CarouselInfo: typeof import('./components/CarouselInfo.vue')['default']
    GoHome: typeof import('./components/GoHome.vue')['default']
    HeroCarousel: typeof import('./components/HeroCarousel.vue')['default']
    HomeCarousel: typeof import('./components/HomeCarousel.vue')['default']
    Hotspot: typeof import('./components/Hotspot.vue')['default']
    Krpano: typeof import('./components/Krpano.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    PageCarousel: typeof import('./components/PageCarousel.vue')['default']
    PhotoCarousel: typeof import('./components/PhotoCarousel.vue')['default']
    PopupCard: typeof import('./components/PopupCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scene: typeof import('./components/Scene.vue')['default']
    Tour: typeof import('./components/Tour.vue')['default']
    WhiteBtn: typeof import('./components/WhiteBtn.vue')['default']
  }
}
